name: Terraform Server Deployment

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: Terraform Server
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5  # Change version if needed

      # Step 3: Terraform Init
      - name: Terraform Init
        run: terraform init
        working-directory: ./server

      # Step 4: Terraform Validate
      - name: Terraform Validate
        run: terraform validate
        working-directory: ./server

      # Step 5: Terraform Plan
      - name: Terraform Plan
        run: terraform plan
        working-directory: ./server

      # Step 6: Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./server
